server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: smallmq

#  shardingsphere:
#    datasource:
#      names:
#        master,slave
#      # 主数据源
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/reggie?characterEncoding=utf-8
#        username: root
#        password: smallmq
#      # 从数据源
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://121.41.82.252:3306/reggie?characterEncoding=utf-8
#        username: smallmq
#        password: ******
#    masterslave:
#      # 读写分离配置
#      load-balance-algorithm-type: round_robin #轮询
#      # 最终的数据源名称
#      name: dataSource
#      # 主库数据源名称
#      master-data-source-name: master
#      # 从库数据源名称列表，多个逗号分隔
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true #开启SQL显示，默认false
  cache:
    redis:
      time-to-live: 1800000
  redis:
    host: localhost
    port: 6379
    database: 0
#  main:
#    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

image:
  file-path: D:\code\java_code\project\reggie_take_out\src\main\resources\image\
logging:
  level:
    root: info
  file:
    name: reggie_take_out.log
